version: '3.8'
services:
  api:
    build:
      context: .
    image: public.ecr.aws/a6o8o7v2/api-image:0.0.11
    ports:
      - "9000:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - environment=local
      - chart_version=0
