---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
data:
  environment: {{ .Values.environment }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config-chart-version
data:
  chart_version: {{ .Values.chart_version }}
