apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
        env:
        - name: environment
          valueFrom:
            configMapKeyRef:
              name: config
              key: environment
        - name: chart_version
          valueFrom:
            configMapKeyRef:
              name: config-chart-version
              key: chart_version

